//react-dates constants
const DEPARTURE_DATE = 'startDate';
const RETURN_DATE = 'endDate';

export default {
  ORIGIN_AIRPORT: 'ORIGIN_AIRPORT',
  DESTINATION_AIRPORT: 'DESTINATION_AIRPORT',
  DEPARTURE_DATE: DEPARTURE_DATE,
  RETURN_DATE: RETURN_DATE
};
