export const SELECT_DEPARTURE_DATE = 'SELECT_DEPARTURE_DATE';
export const SELECT_RETURN_DATE = 'SELECT_RETURN_DATE';
export const CLOSE_DATE_RANGE_SELECTOR = 'CLOSE_DATE_RANGE_SELECTOR';
export const CHANGE_DATE = 'CHANGE_DATE';
