export const SELECT_DEPARTURE_DATE = 'SELECT_DEPARTURE_DATE';
export const SELECT_RETURN_DATE = 'SELECT_RETURN_DATE';
export const CLOSE_DATE_RANGE_SELECTOR = 'CLOSE_DATE_RANGE_SELECTOR';
export const CHANGE_DATE = 'CHANGE_DATE';
export const SELECT_ORIGIN_AIRPORT = 'SELECT_ORIGIN_AIRPORT';
export const SELECT_DESTINATION_AIRPORT = 'SELECT_DESTINATION_AIRPORT';
export const AIRPORT_SELECTED = 'AIRPORT_SELECTED';
export const CLOSE_AIRPORT_SELECTOR = 'CLOSE_AIRPORT_SELECTOR';
